# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' fitting multivariate logistic regression
#' @param Gamma -- dim2 x num_k
#' @param Z2 -- num_sample x dim2
#' @param Eta2 -- dim2 x num_k
#' 
#' 
NULL

#' Expectation
#'
#' @param y -- num_sample x 1
#' @param X -- num_sample x 1
#' @param Z1 -- num_dim1 x num_sample
#' @param Eta1 -- num_dim1 x num_k
#'
NULL

#' Maximization
#'
NULL

#' modified by sun
#' date: 2018-12-30 09:44:04
#' EM algorithm to fit the model
#'
#' @param y -- num_sample x 1
#' @param X -- num_sample x 1
#' @param Z1 -- num_dim1 x num_sample
#' @param Eta1 -- num_dim1 x num_k
#'
#' @return A list
#' 
#' @export
EMstep_extension <- function(yin, Xin, Z1in, Z2in, Win, sigma2ein, sigma2bin, piin, Eta1in, Eta2in, alphain, em_iterin) {
    .Call(`_HOSA_EMstep_extension`, yin, Xin, Z1in, Z2in, Win, sigma2ein, sigma2bin, piin, Eta1in, Eta2in, alphain, em_iterin)
}

#' subgroup analysis using admm 
#'
#' @param Y -- num_sample x 1
#' @param X -- num_sample x 1
#' @param Z -- num_dim x num_sample
#' @param Eta1 -- num_dim1 x num_k
#'
#' @return A list
#' 
#' @return A list
#' 
#' @export
subG_ADMM_extension <- function(Yin, Xin, Win, Zin, Eta1in, lambdain, admm_iterin, tolin) {
    .Call(`_HOSA_subG_ADMM_extension`, Yin, Xin, Win, Zin, Eta1in, lambdain, admm_iterin, tolin)
}

#' @return A list
#' 
#' @export
subG_test <- function(Yin, Xin) {
    .Call(`_HOSA_subG_test`, Yin, Xin)
}

rcpp_hello_world <- function() {
    .Call(`_HOSA_rcpp_hello_world`)
}

